### ISSUE TITLE
[ENHANCEMENT] Update post URL retrieval to remove depreciated code

### ISSUE THREAD

**Issue by mgrove36** [LibrePhotos/librephotos.docs#6]
**Is your feature request related to a problem? Please describe.**
Depreciation of a feature means new implementation required. When building docs, post URL retrieval with a currently unknown method (code causing the issue hasn't yet been located) throws the following error:
```Deprecation: A call to '{% post_url Installation/0000-01-02-arm_install %}' did not match a post using the new matching method of checking name (path-date-slug) equality. Please make sure that you change this tag to match the post's name exactly.```

**Describe the enhancement you'd like**
New implementation of this unknown section of code to replace the depreciated version that is currently used.

**Additional context**
Cause of this issue is currently unknown.

**Comment by erikmakela** [comment]
"0000-01-02-arm_install" as of current does not exist. Looks as though it it was trying to find that file from the test `did not match a post`. Looks as though the file was renamed to "0000-01-02-raspberry-pi.md".

@derneuere Is this issue still persistent?

**Comment by derneuere** [comment]
No this issue is no longer persistent! :)
